import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Image from "next/image";
import Link from "next/link";
import Head from "./head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Smart Cleaner - Seu App de Serviços Domésticos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <Head />
        <main>{children}</main>

        <footer className="bg-gray-900 text-white text-center py-4">
          &copy; {new Date().getFullYear()} Todos os direitos reservados.
        </footer>
      </body>
    </html>
  );
}
